config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from booking.views import BookingIndexView, BookingView, OrderPass

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^booking/$', login_required(BookingView.as_view()), name='booking'),
    url(r'^order-pass/$', login_required(OrderPass.as_view()), name='order-pass'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', login_required(BookingIndexView.as_view()), name='index'),
]

booking/forms.py
# coding: utf-8
import calendar
from datetime import datetime, date, timedelta

from pytils import dt
import floppyforms as forms
from constance import config


def get_months():
    months = []
    for i in range(1, 13):
        months.append((i, i))
    return months


def get_years():
    years = []
    today = date.today()
    for v in range(today.year, today.year + 5):
        years.append((v, v))
    return years


def get_days_staff():
    days = []
    for i in range(1, 32):
        days.append((i, i))
    return days


def get_days():
    days = []
    today = date.today()
    days.append((str(today), dt.ru_strftime(u"%d %B", today, inflected=True)))
    for i in range(1, int(config.ORDERS_DAYS)):
        try:
            next_day = date(today.year, today.month, today.day + timedelta(days=i).days)
        except ValueError:
            _, monthdays = calendar.monthrange(today.year, today.month)
            day = today.day + timedelta(days=i).days
            if monthdays < day:
                surplus = day - monthdays
                next_day = date(today.year, today.month, monthdays) + timedelta(days=surplus)
        days.append((str(next_day), dt.ru_strftime(u"%d %B", next_day, inflected=True)))
    return days


def get_hours():
    hours = []
    for i in range(0, 24):
        hours.append((i, "%02d" % i))
    return hours


def get_minutes():
    minutes = []
    for i in range(0, 60):
        if i % 10 == 0:
            minutes.append((i, "%02d" % i))
    return minutes


def get_initial_day():
    d = str(date.today())
    return d


def get_initial_hour():
    h = datetime.now().hour
    return h


def get_initial_minutes():
    import math
    m = datetime.now().minute
    m = int(math.ceil((m + 10) / 10) * 10)
    if m == 60:
        m = 0
    return m


class BookingForm(forms.Form):
    time = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'field-dropdown-input time', 'placeholder': u'Сколько минут', 'readonly': 'readonly'},
    ))


class OrderForm(forms.Form):
    guest_fio = forms.CharField(label=u'Фамилия и Имя гостя',
                                help_text=u'Если гостей несколько, введите их данные через запятую',
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'required': 'required'},
                                    ))
    visit_day = forms.CharField(label=u'День', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required', 'data-day': get_initial_day()}, choices=get_days()
    ), required=True)
    visit_hour = forms.CharField(label=u'Часы', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required'}, choices=get_hours()
    ), required=True)
    visit_minute = forms.CharField(label=u'Минуты', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required'}, choices=get_minutes()
    ), required=True)

    def clean(self):
        cleaned_data = super(OrderForm, self).clean()
        visit_day = cleaned_data.get("visit_day")
        hours = cleaned_data.get("visit_hour")
        minute = cleaned_data.get("visit_minute")
        try:
            visit_date = visit_day.split('-')
            visit_date = datetime(int(visit_date[0]), int(visit_date[1]), int(visit_date[2]), int(hours), int(minute))
        except Exception, e:
            raise forms.ValidationError(u"Введите правильную дату")

        if datetime.now() > visit_date:
            raise forms.ValidationError(u"Вы не можете заказывать пропуск в прошлое")

        return cleaned_data


class OrderAdminForm(forms.Form):
    guest_fio = forms.CharField(label=u'Фамилия и Имя гостя',
                                help_text=u'Если гостей несколько, введите их данные через запятую',
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'required': 'required'},
                                    ))
    visit_year = forms.CharField(label=u'Год', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required'}, choices=get_years()
    ), required=True)
    visit_month = forms.CharField(label=u'Месяц', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required'}, choices=get_months()
    ), required=True)
    visit_day_staff = forms.CharField(label=u'День', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required'}, choices=get_days_staff()
    ), required=True)

    visit_hour_staff = forms.CharField(label=u'Часы', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required'}, choices=get_hours()
    ), required=True)
    visit_minute_staff = forms.CharField(label=u'Минуты', widget=forms.Select(
        attrs={'class': 'form-control', 'required': 'required'}, choices=get_minutes()
    ), required=True)

    comment = forms.CharField(label=u'К кому идет гость?', help_text=u'Эта информация не отправляется на охрану',
                              widget=forms.TextInput(
                                  attrs={'class': 'form-control', 'required': 'required'}
                              ))

    def clean(self):
        cleaned_data = super(OrderAdminForm, self).clean()
        year = cleaned_data.get("visit_year")
        month = cleaned_data.get("visit_month")
        day = cleaned_data.get("visit_day_staff")
        hours = cleaned_data.get("visit_hour_staff")
        minute = cleaned_data.get("visit_minute_staff")
        try:
            visit_date = datetime(int(year), int(month), int(day), int(hours), int(minute))
        except Exception, e:
            raise forms.ValidationError(u"Введите правильную дату")

        if datetime.now() > visit_date:
            raise forms.ValidationError(u"Вы не можете заказывать пропуск в прошлое")

        return cleaned_data

booking/views.py
# coding: utf-8
import datetime
import json
import pytils
from collections import defaultdict

from django.views.generic import View, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from django.template.loader import render_to_string
from django.shortcuts import render_to_response
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q

from constance import config

from users.models import User
from startups.models import Startup

from .forms import BookingForm, OrderForm, OrderAdminForm, get_months, get_days, get_days_staff,\
    get_hours, get_initial_hour, get_initial_minutes, get_minutes, get_years, get_initial_day
from .models import Booking, MeetingRoom, Order
from .utils import can_book, send_order_pass_mandrill
from users.utils import check_mandrill_status


class BookingIndexView(View):

    def get(self, request):
        return HttpResponseRedirect(reverse('order-pass'))


class BookingView(TemplateView):
    template_name = 'pages/booking.html'

    @staticmethod
    def ajax_render_to_response(context, **response_kwargs):
        return HttpResponse(
            json.dumps(context),
            content_type='application/json',
            **response_kwargs
        )

    def show_messages(self, booking=None):
        html = render_to_string('registration/reg_messages.html', {'messages': messages.get_messages(self.request)})
        data = {'messages': html}
        if booking:
            data['booking_company'] = booking.company
            data['booking_user'] = booking.user.get_full_name()
            data['booking_id'] = booking.id
            data['addevent_data'] = {'summary': u'Бронь переговорной "%s"' % booking.meeting_room.title,
                                     'start': booking.start.strftime("%m-%d-%Y %H:%M:%S"),
                                     'end': booking.end.strftime("%m-%d-%Y %H:%M:%S"),
                                     'description': u'Бронь переговорной "%s"' % booking.meeting_room.title,
                                     'location': u'Москва, Серебрянническая наб., 29, 7-й этаж, переговорная "%s"' % booking.meeting_room.title}
        return self.ajax_render_to_response(data)

    def calendar_day(self, day):
        today = timezone.now()
        cur_day = today + datetime.timedelta(days=day)

        prev = cur_day - datetime.timedelta(days=1)
        prev_day = pytils.dt.ru_strftime(u"%d %B", prev, inflected=True)

        next = cur_day + datetime.timedelta(days=1)
        next_day = pytils.dt.ru_strftime(u"%d %B", next, inflected=True)

        today_min = datetime.datetime.combine(cur_day, datetime.time.min)
        today_max = datetime.datetime.combine(cur_day, datetime.time.max)
        bookings = Booking.objects.filter(start__range=(today_min, today_max))
        cur_data = {}

        for booking in bookings:
            owner = 'own' if booking.user == self.request.user else 'alien'
            start = str(booking.start.hour) + ':' + str(booking.start.minute)
            duration = (booking.end - booking.start).seconds / 60

            if owner == 'own':
                if booking.company:
                    company = booking.company
                else:
                    company = u'Забронировано вами'
            elif booking.user.is_staff and booking.company == booking.user.get_full_name():
                company = 'Акселератор'
            else:
                company = booking.company

            creator = booking.user.get_full_name()

            cur_data[str(booking.id)] = {'company': company, 'start': start, 'duration': duration, 'creator': creator,
                                         'owner': owner, 'nv': str(booking.meeting_room.id),
                                         'addevent_data': {
                                             'summary': u'Бронь переговорной "%s"' % booking.meeting_room.title,
                                             'start': booking.start.strftime("%m-%d-%Y %H:%M:%S"),
                                             'end': booking.end.strftime("%m-%d-%Y %H:%M:%S"),
                                             'description': u'Бронь переговорной "%s"' % booking.meeting_room.title,
                                             'location': u'Москва, Серебрянническая наб., 29, 7-й этаж, '
                                                         u'переговорная "%s"' % booking.meeting_room.title
                                         }
            }
        is_staff = self.request.user.is_staff
        data = {'next': {'id': day + 1, 'day': next_day}, 'prev': {'id': day - 1, 'day': prev_day}, 'is_staff': is_staff,
                'cur_id': day, 'cur': pytils.dt.ru_strftime(u"%d %B, %A", cur_day, inflected=True), 'cur_data': cur_data
                }
        return data

    def get_context_data(self, **kwargs):
        context = super(BookingView, self).get_context_data(**kwargs)
        if self.request.user.is_staff:
            days_count = 10000
        else:
            days_count = config.PROFILE_BOOKING_CALENDAR_DAYS
        form = BookingForm()
        nv = MeetingRoom.objects.all()
        startups = Startup.objects.all()
        hours = ['8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00',
                 '16:00', '17:00', '18:00', '19:00', '20:00']

        return {'form': form, 'nv': nv, 'hours': hours, 'days_count': days_count, 'startups': startups}

    def get(self, request, *args, **kwargs):
        if request.is_ajax and request.GET.get('day_id'):
            calendar_day = self.calendar_day(int(request.GET.get('day_id')))
            return self.ajax_render_to_response({'calendar_day': calendar_day})
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        start = request.POST.get('start')
        time = request.POST.get('time')
        startup = request.POST.get('startup')
        meeting_room_id = request.POST.get('meeting_room')
        cur_day = request.POST.get('cur_day')

        booking_id = request.POST.get('booking_id')
        booking_type = request.POST.get('type')
        if booking_type and booking_type == 'remove_booking' and booking_id:
            try:
                booking = Booking.objects.get(id=int(booking_id))
                if request.user.is_staff or request.user == booking.user:
                    booking.delete()
                    messages.info(request, u'Бронь удалена', extra_tags='notification')
                    return self.show_messages()
                else:
                    messages.error(request, u'Вам отказано в доступе к операции', extra_tags='notification')
                    return self.show_messages()
            except Booking.DoesNotExist:
                messages.info(request, u'Данной брони уже не существует. Обновите страницу.', extra_tags='notification')
                return self.show_messages()

        nv = MeetingRoom.objects.get(id=int(meeting_room_id))

        today = datetime.datetime.today() + datetime.timedelta(days=int(cur_day))
        s = start.split(':')
        start = datetime.datetime(today.year, today.month, today.day, int(s[0]), int(s[1]))
        # set min time if time data was bugged
        if time:
            t = int(time.split(' ')[0])
        else:
            t = 30
        end = start + datetime.timedelta(minutes=t)

        already_booked = Booking.objects.filter(Q(start__gt=start, start__lt=end, meeting_room=nv)
                                                | Q(end__gt=start, end__lt=end, meeting_room=nv)).count()
        if already_booked > 0:
            messages.warning(request, u'На это время уже оформлен заказ', extra_tags='notification')
            return self.show_messages()

        if startup:
            company = startup
        else:
            av_time = True
            available_time = 120
            startups = Startup.objects.filter(members__id__exact=request.user.id)
            if len(startups):
                startup = startups[0]
                company = startup.name
                if not request.user.is_staff:
                    available_time = can_book(today, company)
                    if not available_time:
                        av_time = None

            else:
                company = request.user.get_full_name()
                if not request.user.is_staff:
                    available_time = can_book(today, company)
                    if not available_time:
                        av_time = None

            if not av_time:
                messages.warning(request, u'Вы не может больше бронировать переговорную на этот день',
                                 extra_tags='notification')
                return self.show_messages()

            if available_time < t:
                messages.warning(request, u'Вы можете забронировать переговорную максимум '
                                          u'еще на %s минут на этот день' % int(available_time),
                                 extra_tags='notification')
                return self.show_messages()

        booking, created = Booking.objects.get_or_create(start=start, end=end, company=company,
                                                         meeting_room=nv, user=request.user)
        messages.info(request, u'Бронь заказана', extra_tags='notification')
        return self.show_messages(booking)


class OrderPass(TemplateView):
    template_name = 'pages/order_pass.html'

    def get_orders(self):
        user = self.request.user
        if user.is_staff:
            users = User.objects.filter(is_staff=True)
            orders = []
            for user in users:
                orders.extend(Order.objects.filter(user=user))
            orders.sort(key=lambda x: x.date, reverse=True)

templates/pages/order_pass.html
{% extends 'pages/userpage.html' %}
{% load staticfiles floppyforms pytils_dt pytils_numeral booking_tags %}

{% block title %}Заказ пропусков{% endblock title %}
{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/registration.css' %}"/>
<link href="{% static 'css/jquery.toastmessage.css' %}" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}"/>
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<style >
    .tooltip-inner {
        width: 200px;
        max-width: 500px;
    }
    .order-pass-status {
        font-size: 16px;
    }
</style>
{% endblock extracss %}

{% block top %}
<div class="container container-top"><div class="row">
    <div class="page-header">
      <h1>{{ request.user.get_full_name }}
          <small>заказ пропуска в #tceh
            <a href="/" class="header-logo-link pull-right my-page-header-link">
                <img src="{% static 'img/logo.png' %}" />
            </a>
          </small></h1>
    </div>
</div></div>
{% endblock top %}

{% block modals %}{% endblock modals %}

{% block content %}
<div class="col-md-10">
    <div class="row">
        <div class="col-md-7 col-md-offset-1">
            <h3>Форма заказа пропуска</h3>
            <form id="order_pass_form" novalidate data-toggle="validator" role="form" method="post" action="{% url 'order-pass' %}">{% csrf_token %}
                {% form form using %}
                {% formrow form.guest_fio using "floppyforms/rows/div.html" %}
                <div class="form-group">
                    <label>Дата и время визита:</label>
                    {% if form.non_field_errors %}
                        <div class="has-error">
                            <div class="help-block with-errors">{{ form.non_field_errors|striptags }}</div>
                        </div>
                    {% endif %}
                </div>
                {% formrow form.visit_hour using "floppyforms/rows/div.html" %}
                {% formrow form.visit_minute using "floppyforms/rows/div.html" %}
                {% formrow form.visit_day using "floppyforms/rows/div.html" %}

                {% formrow form.visit_hour_staff using "floppyforms/rows/div.html" %}
                {% formrow form.visit_minute_staff using "floppyforms/rows/div.html" %}
                {% formrow form.visit_day_staff using "floppyforms/rows/div.html" %}
                {% formrow form.visit_month using "floppyforms/rows/div.html" %}
                {% formrow form.visit_year using "floppyforms/rows/div.html" %}


                {% formrow form.comment using "floppyforms/rows/div.html" %}
                {% endform %}

              <button type="submit" class="btn btn-success">Отправить заявку</button>
            </form>
        </div>
    </div>

    {% if orders %}
    <div class="row">
        <div class="col-md-7 col-md-offset-1">
            <h3>Ранее заказанные пропуска</h3>

            {% regroup orders by date|date:"j F" as orders_by_day %}
            {% for group in orders_by_day %}
                <h4>{{ group.list.0.date|ru_strftime:"%d %B, %A" }}</h4>
                <div class="row">
                    <div class="col-md-11 col-md-offset-1">
                        <table class="table">
                            <tr>
                                <th>Фамилия, Имя</th>
                                <th>Дата, время</th>
                                {% if request.user.is_staff %}
                                    <th>Комментарий</th>
                                {% endif %}
                                <th>Статус</th>
                            </tr>
                            {% for order in group.list %}
                                <tr>
                                    <td style="font-size: 80%;">{{ order.guest_fio }}</td>
                                    <td style="font-size: 80%;">{{ order.date|ru_strftime:"%d %B %Y, %H:%M" }}</td>
                                    {% if request.user.is_staff %}
                                        <td style="font-size: 80%;">{{ order.comment }}</td>
                                    {% endif %}
                                    <td>
                                        {% if order.status == '0' %}
                                            <span class="glyphicon glyphicon-time order-pass-status" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="{{ order.display_status }} {{ order.date|get_time_for_status|ru_strftime:"%d %B в %H:%M" }}"></span>
                                        {% elif order.status == '1' %}
                                            <span class="glyphicon glyphicon-share order-pass-status" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="{{ order.display_status }}"></span>
                                        {% elif order.status == '2' %}
                                            <span class="glyphicon glyphicon-check order-pass-status" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="{{ order.display_status }}"></span>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            {% endfor %}

            <ul class="pagination pagination-centered">
                {% if orders_group.has_previous %}
                    <li><a href="?page=1"><<</a></li>
                    <li><a href="?page={{ orders_group.previous_page_number }}"><</a></li>
                {% endif %}

                {% for i in paginator.page_range %}
                    <li {% if orders_group.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
                {% endfor %}

                {% if orders_group.has_next %}
                    <li><a href="?page={{ orders_group.next_page_number }}">></a></li>
                    <li><a href="?page={{ orders_group.paginator.num_pages }}">>></a></li>
                {% endif %}
            </ul>

        </div>
    </div>
    {% endif %}

</div>
{% endblock content %}

{% block forms %}{% endblock forms %}

{% block js %}
    <script src="{% static 'js/jquery.toastmessage.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.validator.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script type="text/javascript">
        $(function(){
            var hour_input, minute_input, day_input;

            if ($('#id_visit_hour_staff').length > 0){
                hour_input = $('#id_visit_hour_staff');
                minute_input = $('#id_visit_minute_staff');
            }
            else{
                hour_input = $('#id_visit_hour');
                minute_input = $('#id_visit_minute');
                day_input = $('#id_visit_day')
            }
            var d = new Date();
            var m = d.getMinutes();
            var v = hour_input.val();

            if(typeof(day_input) !== 'undefined'){
                var day = d.getDay();
                var init_day = day_input.attr('data-day');
                day_input.val(init_day)
            }
            if (m >= 50 && minute_input.val() == 0){
                var new_h = parseInt(v) + 1;
                if (new_h == 24){
                    new_h = 0;
                    if(typeof(day_input) !== 'undefined'){
                        var opt = day_input.find("option:selected").next();
                        day_input.val(opt.val())
                    }
                }
                hour_input.val(new_h);
            }

            $('#order_pass_form').validator();

            var update_controlls = function(){
                var d = new Date();
                var m = d.getMinutes();
                var h = d.getHours();
                var round_m = Math.ceil(m / 10) * 10;

                if (round_m == m){
                    round_m += 10;
                }

                if(round_m == 60){
                    round_m = 0;
                    h += 1;
                    if (h == 24){
                        h = 0;
                        if(typeof(day_input) !== 'undefined'){
                            var opt = day_input.find("option:selected").next();
                            day_input.val(opt.val())
                        }
                    }
                }
                minute_input.val(round_m);
                hour_input.val(h);
            };
            setInterval(update_controlls, 5 * 60 * 1000);

            $('#order_pass_form').on('submit',function(e){
                var $form = $(this);
                if ($form.data('submitted') === true) {
                  e.preventDefault();
                } else {
                  $form.data('submitted', true);
                }
            });
        });
    </script>
{% endblock js %}

templates/pages/userpage.html
{% load staticfiles floppyforms %}
<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    {% block first_head_static %}
    {% endblock first_head_static %}
    {% block head_static %}
	<link href="{% static 'favicon.ico' %}" rel="shortcut icon" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/iidf.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}"/>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
    <script type="text/javascript" src="https://addthisevent.com/libs/1.6.0/ate.min.js"></script>
    {% endblock head_static %}
	<title>{% block title %}Профиль {{request.user.get_full_name}}{% endblock title %}</title>
    {% block head_script %}
	<script type="text/javascript">
		$(document).ready(function() {

			$('[data-toggle="tooltip"]').tooltip({
				'placement': 'bottom'
			});

		}); //END $(document).ready()
		$('[data-dismiss="alert"]').ready(function() {
			$(".alert").alert();
		});


		function showempbal() {
			$('#divemp').hide();
			$('#notemp').show();
		}

		function accept(eid) {
			$('#data-accept').val("1");
			$('#emplid').val(eid);
			$('#compemp').submit();
		}

		function decline(eid) {
			if (confirm('Вы уверены?')) {
				$('#data-accept').val("0");
				$('#emplid').val(eid);
				$('#compemp').submit();
			}
		}
		function visibility(form,alt)
		{
			$('#'+alt).removeClass('in');
			$('#'+alt).addClass('out');
			$('#'+form).scrollTop();
		}
		var monthprice=parseInt("{{psumm}}");
		function pay_price(sel)
		{
			newprice=parseInt($(sel).val())*monthprice;
			$('#pay_price').html("К оплате: "+newprice+" руб.");
		}



        function select_rate(id)
        {
            $('#newrate').val(id);
        }

        select_stage=0;
        selected_str="";
        function select_pay()
        {
            if(select_stage)
            {
                $("select[id^=mpay]").each(function() {
                    selected_str+=$(this).attr('id')+"="+$( this ).val()+";";
                });
                $("#selected_str").val(selected_str);
                $("#pay_form").submit();
            }
            else
            {
                $("p[id^=chbutton]").css('display','none');
                $("p[id^=delbutton]").css('display','none');
                $("div[id^=mselect]").css('display','block');
                $("#pay_button").html("Оплатить по месяцам");
                select_stage=1;
            }
        }
        function validate_add()
        {
            srate=$('#srate').val();
            if(srate>"0")
            {
                email=$('#newemail').val();
                var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
                if(re.test(email)) return true;
                else
                {
                    alert("Введите email");
                    return false;
                }
            }
            else
            {
                alert("Выберите тариф");
                return false;
            }
        }


	</script>
    {% endblock head_script %}
    {% block extracss %}
        <link href="{% static 'css/jquery.toastmessage.css' %}" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}"/>
        <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
        <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    {% endblock extracss %}
</head>

<body>
    {% block top %}
        <div class="container container-top"><div class="row">
            <div class="page-header">
                <div class="">
                    <a style="margin-left: 50px" href="/" class="header-logo-link pull-right my-page-header-link changepswd">
                        <img src="{% static 'img/logo.png' %}" />
                    </a>

                </div>

            </div>
        </div></div>
    {% endblock top %}

	<div class="container">
		<div class="row">
			<div class="col-md-2 left">

                {% block nav %}
                    <ul class="nav nav-pills nav-stacked">
                        {% if request.user.can_book_meeting_room %}
                            <li {%if request.path == '/booking/' %}class="active"{% endif %}><a href="{% url 'booking' %}">Переговорки</a></li>
                            <li {%if request.path == '/order-pass/' %}class="active"{% endif %}><a href="{% url 'order-pass' %}">Заказ пропусков</a></li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}">Выход</a></li>
                        {% endif %}
                    </ul>
                {% endblock nav %}

                {% block mes %}{% endblock mes %}
			</div>
            {% if message %}
                <div class="col-md-10 center alert alert-warning alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  {{ message }}
                </div>
            {% endif %}
            {% block content %}
			<div class="col-md-10 center">
				<div class="row">
					<div class="page-header reginfo">
						<h3>Личные данные</h3>
					</div>
				</div>

			</div>
            {% endblock content %}
		</div>
	</div>

    {% block forms %}{% endblock forms %}

    {% block js %}
    {% endblock js %}

    {% block extrajs %}{% endblock extrajs %}
</body>

</html>